name: Shared FuncNet Workflow Steps

on:
  workflow_call:
    inputs:
      configuration:
        description: 'Build configuration (Debug/Release)'
        required: false
        default: 'Debug'
        type: string

jobs:
  build-test-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore
      
      - name: Run FuncNet.Generator
        run: dotnet run --project FuncNet.Generator/FuncNet.Generator.csproj --configuration ${{ inputs.configuration }} --no-build
      
      - name: Check for changes in generated files
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected in generated files after running FuncNet.Generator:"
            git status --porcelain
            echo "Please regenerate the code and commit the changes."
            exit 1
          else
            echo "No changes detected. Generated files are up to date."
          fi
      
      - name: Test
        run: dotnet test --configuration ${{ inputs.configuration }} --no-build --verbosity normal
