name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run FuncNet.Generator
      run: dotnet run --project FuncNet.Generator/FuncNet.Generator.csproj --configuration Release --no-build
    
    - name: Check for changes in generated files
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected in generated files after running FuncNet.Generator:"
          git status --porcelain
          echo "Please regenerate the code and commit the changes before creating a release."
          exit 1
        else
          echo "No changes detected. Generated files are up to date."
        fi
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Pack
      run: dotnet pack FuncNet/FuncNet.csproj --configuration Release --no-build --output nupkgs
    
    - name: Push to NuGet
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: nupkgs/*.nupkg
