name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  validate:
    uses: ./.github/workflows/build-test-validate.yml
    with:
      configuration: 'Release'
    secrets: inherit

  publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore FuncNet/FuncNet.csproj

    - name: Build
      run: dotnet build FuncNet/FuncNet.csproj --configuration Release --no-restore

    - name: Pack FuncNet
      run: dotnet pack FuncNet/FuncNet.csproj --configuration Release --no-build -o ./artifacts
    
    - name: Pack FuncNet.Analyzers
      run: dotnet pack FuncNet.Analyzers/FuncNet.Analyzers.csproj --configuration Release --no-build -o ./artifacts
    
    - name: Push to NuGet
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: nupkgs/*.nupkg
